import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-black text-white sticky top-0 z-50">
          <nav className="max-w-3xl mx-auto px-8 py-4 flex justify-between items-center">
            <h1 className="text-2xl font-bold">
              <a href="/" className="hover:text-gray-300">Home</a>
            </h1>
            <ul className="flex gap-6">
              <li><a href="/blog" className="hover:text-gray-300">Blog</a></li>
              <li><a href="/about" className="hover:text-gray-300">About</a></li>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
